ttc_graph = {
    # line 1
    'Vaughan Metropolitan Centre': [('Highway 407', 4)],
    'Highway 407': [('Vaughan Metropolitan Centre', 4), ('Pioneer Village', 3)],
    'Pioneer Village': [('Highway 407', 3), ('York University', 3)],
    'York University': [('Pioneer Village', 3), ('Finch West', 4)],
    'Finch West': [('York University', 4), ('Downsview Park', 3)],
    'Downsview Park': [('Finch West', 3), ('Sheppard West', 2)],
    'Sheppard West': [('Downsview Park', 2), ('Wilson', 3)],
    'Wilson': [('Sheppard West', 3), ('Yorkdale', 4)],
    'Yorkdale': [('Wilson', 4), ('Lawrence West', 2)],
    'Lawrence West': [('Yorkdale', 2), ('Glencairn', 2)],
    'Glencairn': [('Lawrence West', 2), ('Cedarvale', 3)],
    'Cedarvale': [('Glencairn', 3), ('St. Clair West', 4)],
    'St. Clair West': [('Cedarvale', 4), ('Dupont', 2)],
    'Dupont': [('St. Clair West', 2), ('Spadina', 2)],

    # change lines
    'Spadina': [('Dupont', 2), ('St. George', 2), ('Bathurst', 3)],
    'St. George': [('Spadina', 2), ('Museum', 2), ('Bay', 2)],

    'Museum': [('St. George', 2), ("Queen's Park", 2)],
    "Queen's Park": [('Museum', 2), ('St. Patrick', 2)],
    'St. Patrick': [("Queen's Park", 2), ('Osgoode', 2)],
    'Osgoode': [('St. Patrick', 2), ('St. Andrew', 2)],
    'St. Andrew': [('Osgoode', 2), ('Union', 3)],
    'Union': [('St. Andrew', 3), ('King', 2)],
    'King': [('Union', 2), ('Queen', 2)],
    'Queen': [('King', 2), ('Dundas', 1)],
    'Dundas': [('Queen', 1), ('College', 2)],
    'College': [('Dundas', 2), ('Wellesley', 2)],
    'Wellesley': [('College', 2), ('Bloor-Yonge', 2)],

    # Change lines
    'Bloor-Yonge': [('Wellesley', 2), ('Rosedale', 3), ('Bay', 2), ('Sherbourne', 4), ('Bay', 2)],

    'Rosedale': [('Bloor-Yonge', 3), ('Summerhill', 2)],
    'Summerhill': [('Rosedale', 2), ('St. Clair', 2)],
    'St. Clair': [('Summerhill', 2), ('Davisville', 2)],
    'Davisville': [('St. Clair', 2), ('Eglinton', 3)],
    'Eglinton': [('Davisville', 3), ('Lawrence', 4)],
    'Lawrence': [('Eglinton', 4), ('York Mills', 5)],
    'York Mills': [('Lawrence', 5), ('Sheppard-Yonge', 3)],
    'Sheppard-Yonge': [('York Mills', 3), ('North York Centre', 4)],
    'North York Centre': [('Sheppard-Yonge', 4), ('Finch', 4)],
    'Finch': [('North York Centre', 4)],

    # Line 2 west side
    'Kipling': [('Islington', 4)],
    'Islington': [('Kipling', 4), ('Royal York', 3)],
    'Royal York': [('Islington', 3), ('Old Mill', 2)],
    'Old Mill': [('Royal York', 2), ('Jane', 3)],
    'Jane': [('Old Mill', 3), ('Runnymede', 2)],
    'Runnymede': [('Jane', 2), ('High Park', 2)],
    'High Park': [('Runnymede', 2), ('Keele', 3)],
    'Keele': [('High Park', 3), ('Dundas West', 2)],
    'Dundas West': [('Keele', 2), ('Lansdowne', 3)],
    'Lansdowne': [('Dundas West', 3), ('Dufferin', 2)],
    'Dufferin': [('Lansdowne', 2), ('Ossington', 2)],
    'Ossington': [('Dufferin', 2), ('Christie', 2)],
    'Christie': [('Ossington', 2), ('Bathurst', 2)],
    'Bathurst': [('Christie', 2), ('Spadina', 3)],

    # between east and west side
    'Bay': [('St. George', 2), ('Bloor-Yonge', 2)],

    # Line 2 east side
    'Sherbourne': [('Bloor-Yonge', 4), ('Castle Frank', 3)],
    'Castle Frank': [('Sherbourne', 3), ('Broadview', 3)],
    'Broadview': [('Castle Frank', 3), ('Chester', 2)],
    'Chester': [('Broadview', 2), ('Pape', 3)],
    'Pape': [('Chester', 3), ('Donlands', 2)],
    'Donlands': [('Pape', 2), ('Greenwood', 2)],
    'Greenwood': [('Donlands', 2), ('Coxwell', 3)],
    'Coxwell': [('Greenwood', 3), ('Woodbine', 2)],
    'Woodbine': [('Coxwell', 2), ('Main Street', 4)],
    'Main Street': [('Woodbine', 4), ('Victoria Park', 3)],
    'Victoria Park': [('Main Street', 3), ('Warden', 4)],
    'Warden': [('Victoria Park', 4), ('Kennedy', 5)],
    'Kennedy': [('Warden', 5)],
}
